services:
  minio:
    image: minio/minio
    container_name: micont
    # /buckets folder on container where S3 store
    command: server /buckets --console-address ":9001"
    environment:
      MINIO_ROOT_USER: nail
      MINIO_ROOT_PASSWORD: password
      MINIO_SERVER_URL: "https://localhost:9000"
      MINIO_BROWSER_REDIRECT_URL: "https://localhost:9001" # Console HTTPS
    volumes:
      # Sync S3
      - type: volume
        source: S3Volume
        # same as in command
        target: /buckets
      # Copy TLS certs, Read Only mode
      - ./certs:/root/.minio/certs:ro
    healthcheck:
      test: [ "CMD", "curl", "-f", "https://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      # API: http://127.0.0.1:9000 
      - target: 9000
        published: 9000
        protocol: tcp
      # WebUI: http://127.0.0.1:9001
      - target: 9001
        published: 9001
        protocol: tcp
    restart: no
    networks:
      - localnet

volumes:
  S3Volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      # /path/to/data
      device: ./S3Bucks

networks:
  localnet:
    driver: bridge
