// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GkeeperClient is the client API for Gkeeper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GkeeperClient interface {
	RegisterUser(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	LoginUser(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	PutText(ctx context.Context, in *PutTextRequest, opts ...grpc.CallOption) (*PutTextResponse, error)
	PutFile(ctx context.Context, in *PutFileRequest, opts ...grpc.CallOption) (*PutFileResponse, error)
	ListObjects(ctx context.Context, in *ListObjectsRequest, opts ...grpc.CallOption) (*ListObjectsResponse, error)
	UploadFile(ctx context.Context, opts ...grpc.CallOption) (Gkeeper_UploadFileClient, error)
	ProbaFunc(ctx context.Context, opts ...grpc.CallOption) (Gkeeper_ProbaFuncClient, error)
}

type gkeeperClient struct {
	cc grpc.ClientConnInterface
}

func NewGkeeperClient(cc grpc.ClientConnInterface) GkeeperClient {
	return &gkeeperClient{cc}
}

func (c *gkeeperClient) RegisterUser(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/gorsovet.gkeeper/RegisterUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gkeeperClient) LoginUser(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/gorsovet.gkeeper/LoginUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gkeeperClient) PutText(ctx context.Context, in *PutTextRequest, opts ...grpc.CallOption) (*PutTextResponse, error) {
	out := new(PutTextResponse)
	err := c.cc.Invoke(ctx, "/gorsovet.gkeeper/PutText", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gkeeperClient) PutFile(ctx context.Context, in *PutFileRequest, opts ...grpc.CallOption) (*PutFileResponse, error) {
	out := new(PutFileResponse)
	err := c.cc.Invoke(ctx, "/gorsovet.gkeeper/PutFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gkeeperClient) ListObjects(ctx context.Context, in *ListObjectsRequest, opts ...grpc.CallOption) (*ListObjectsResponse, error) {
	out := new(ListObjectsResponse)
	err := c.cc.Invoke(ctx, "/gorsovet.gkeeper/ListObjects", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gkeeperClient) UploadFile(ctx context.Context, opts ...grpc.CallOption) (Gkeeper_UploadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &Gkeeper_ServiceDesc.Streams[0], "/gorsovet.gkeeper/UploadFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &gkeeperUploadFileClient{stream}
	return x, nil
}

type Gkeeper_UploadFileClient interface {
	Send(*Chunk) error
	Recv() (*Chunk, error)
	grpc.ClientStream
}

type gkeeperUploadFileClient struct {
	grpc.ClientStream
}

func (x *gkeeperUploadFileClient) Send(m *Chunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gkeeperUploadFileClient) Recv() (*Chunk, error) {
	m := new(Chunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gkeeperClient) ProbaFunc(ctx context.Context, opts ...grpc.CallOption) (Gkeeper_ProbaFuncClient, error) {
	stream, err := c.cc.NewStream(ctx, &Gkeeper_ServiceDesc.Streams[1], "/gorsovet.gkeeper/ProbaFunc", opts...)
	if err != nil {
		return nil, err
	}
	x := &gkeeperProbaFuncClient{stream}
	return x, nil
}

type Gkeeper_ProbaFuncClient interface {
	Send(*Chunk) error
	CloseAndRecv() (*Chunk, error)
	grpc.ClientStream
}

type gkeeperProbaFuncClient struct {
	grpc.ClientStream
}

func (x *gkeeperProbaFuncClient) Send(m *Chunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gkeeperProbaFuncClient) CloseAndRecv() (*Chunk, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Chunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GkeeperServer is the server API for Gkeeper service.
// All implementations must embed UnimplementedGkeeperServer
// for forward compatibility
type GkeeperServer interface {
	RegisterUser(context.Context, *RegisterRequest) (*RegisterResponse, error)
	LoginUser(context.Context, *LoginRequest) (*LoginResponse, error)
	PutText(context.Context, *PutTextRequest) (*PutTextResponse, error)
	PutFile(context.Context, *PutFileRequest) (*PutFileResponse, error)
	ListObjects(context.Context, *ListObjectsRequest) (*ListObjectsResponse, error)
	UploadFile(Gkeeper_UploadFileServer) error
	ProbaFunc(Gkeeper_ProbaFuncServer) error
	mustEmbedUnimplementedGkeeperServer()
}

// UnimplementedGkeeperServer must be embedded to have forward compatible implementations.
type UnimplementedGkeeperServer struct {
}

func (UnimplementedGkeeperServer) RegisterUser(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterUser not implemented")
}
func (UnimplementedGkeeperServer) LoginUser(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginUser not implemented")
}
func (UnimplementedGkeeperServer) PutText(context.Context, *PutTextRequest) (*PutTextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutText not implemented")
}
func (UnimplementedGkeeperServer) PutFile(context.Context, *PutFileRequest) (*PutFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutFile not implemented")
}
func (UnimplementedGkeeperServer) ListObjects(context.Context, *ListObjectsRequest) (*ListObjectsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListObjects not implemented")
}
func (UnimplementedGkeeperServer) UploadFile(Gkeeper_UploadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedGkeeperServer) ProbaFunc(Gkeeper_ProbaFuncServer) error {
	return status.Errorf(codes.Unimplemented, "method ProbaFunc not implemented")
}
func (UnimplementedGkeeperServer) mustEmbedUnimplementedGkeeperServer() {}

// UnsafeGkeeperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GkeeperServer will
// result in compilation errors.
type UnsafeGkeeperServer interface {
	mustEmbedUnimplementedGkeeperServer()
}

func RegisterGkeeperServer(s grpc.ServiceRegistrar, srv GkeeperServer) {
	s.RegisterService(&Gkeeper_ServiceDesc, srv)
}

func _Gkeeper_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GkeeperServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gorsovet.gkeeper/RegisterUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GkeeperServer).RegisterUser(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gkeeper_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GkeeperServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gorsovet.gkeeper/LoginUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GkeeperServer).LoginUser(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gkeeper_PutText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GkeeperServer).PutText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gorsovet.gkeeper/PutText",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GkeeperServer).PutText(ctx, req.(*PutTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gkeeper_PutFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GkeeperServer).PutFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gorsovet.gkeeper/PutFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GkeeperServer).PutFile(ctx, req.(*PutFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gkeeper_ListObjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListObjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GkeeperServer).ListObjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gorsovet.gkeeper/ListObjects",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GkeeperServer).ListObjects(ctx, req.(*ListObjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gkeeper_UploadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GkeeperServer).UploadFile(&gkeeperUploadFileServer{stream})
}

type Gkeeper_UploadFileServer interface {
	Send(*Chunk) error
	Recv() (*Chunk, error)
	grpc.ServerStream
}

type gkeeperUploadFileServer struct {
	grpc.ServerStream
}

func (x *gkeeperUploadFileServer) Send(m *Chunk) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gkeeperUploadFileServer) Recv() (*Chunk, error) {
	m := new(Chunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Gkeeper_ProbaFunc_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GkeeperServer).ProbaFunc(&gkeeperProbaFuncServer{stream})
}

type Gkeeper_ProbaFuncServer interface {
	SendAndClose(*Chunk) error
	Recv() (*Chunk, error)
	grpc.ServerStream
}

type gkeeperProbaFuncServer struct {
	grpc.ServerStream
}

func (x *gkeeperProbaFuncServer) SendAndClose(m *Chunk) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gkeeperProbaFuncServer) Recv() (*Chunk, error) {
	m := new(Chunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Gkeeper_ServiceDesc is the grpc.ServiceDesc for Gkeeper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Gkeeper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gorsovet.gkeeper",
	HandlerType: (*GkeeperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterUser",
			Handler:    _Gkeeper_RegisterUser_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _Gkeeper_LoginUser_Handler,
		},
		{
			MethodName: "PutText",
			Handler:    _Gkeeper_PutText_Handler,
		},
		{
			MethodName: "PutFile",
			Handler:    _Gkeeper_PutFile_Handler,
		},
		{
			MethodName: "ListObjects",
			Handler:    _Gkeeper_ListObjects_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadFile",
			Handler:       _Gkeeper_UploadFile_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ProbaFunc",
			Handler:       _Gkeeper_ProbaFunc_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/gorsovet.proto",
}
