// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GkeeperClient is the client API for Gkeeper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GkeeperClient interface {
	RegisterUser(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	LoginUser(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// загрузка на сервер. от клиента серверу stream of Chunks, ответ обычный
	Greceiver(ctx context.Context, opts ...grpc.CallOption) (Gkeeper_GreceiverClient, error)
	ListObjects(ctx context.Context, in *ListObjectsRequest, opts ...grpc.CallOption) (*ListObjectsResponse, error)
}

type gkeeperClient struct {
	cc grpc.ClientConnInterface
}

func NewGkeeperClient(cc grpc.ClientConnInterface) GkeeperClient {
	return &gkeeperClient{cc}
}

func (c *gkeeperClient) RegisterUser(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/gorsovet.gkeeper/RegisterUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gkeeperClient) LoginUser(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/gorsovet.gkeeper/LoginUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gkeeperClient) Greceiver(ctx context.Context, opts ...grpc.CallOption) (Gkeeper_GreceiverClient, error) {
	stream, err := c.cc.NewStream(ctx, &Gkeeper_ServiceDesc.Streams[0], "/gorsovet.gkeeper/Greceiver", opts...)
	if err != nil {
		return nil, err
	}
	x := &gkeeperGreceiverClient{stream}
	return x, nil
}

type Gkeeper_GreceiverClient interface {
	Send(*ReceiverChunk) error
	CloseAndRecv() (*ReceiverResponse, error)
	grpc.ClientStream
}

type gkeeperGreceiverClient struct {
	grpc.ClientStream
}

func (x *gkeeperGreceiverClient) Send(m *ReceiverChunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gkeeperGreceiverClient) CloseAndRecv() (*ReceiverResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ReceiverResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gkeeperClient) ListObjects(ctx context.Context, in *ListObjectsRequest, opts ...grpc.CallOption) (*ListObjectsResponse, error) {
	out := new(ListObjectsResponse)
	err := c.cc.Invoke(ctx, "/gorsovet.gkeeper/ListObjects", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GkeeperServer is the server API for Gkeeper service.
// All implementations must embed UnimplementedGkeeperServer
// for forward compatibility
type GkeeperServer interface {
	RegisterUser(context.Context, *RegisterRequest) (*RegisterResponse, error)
	LoginUser(context.Context, *LoginRequest) (*LoginResponse, error)
	// загрузка на сервер. от клиента серверу stream of Chunks, ответ обычный
	Greceiver(Gkeeper_GreceiverServer) error
	ListObjects(context.Context, *ListObjectsRequest) (*ListObjectsResponse, error)
	mustEmbedUnimplementedGkeeperServer()
}

// UnimplementedGkeeperServer must be embedded to have forward compatible implementations.
type UnimplementedGkeeperServer struct {
}

func (UnimplementedGkeeperServer) RegisterUser(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterUser not implemented")
}
func (UnimplementedGkeeperServer) LoginUser(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginUser not implemented")
}
func (UnimplementedGkeeperServer) Greceiver(Gkeeper_GreceiverServer) error {
	return status.Errorf(codes.Unimplemented, "method Greceiver not implemented")
}
func (UnimplementedGkeeperServer) ListObjects(context.Context, *ListObjectsRequest) (*ListObjectsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListObjects not implemented")
}
func (UnimplementedGkeeperServer) mustEmbedUnimplementedGkeeperServer() {}

// UnsafeGkeeperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GkeeperServer will
// result in compilation errors.
type UnsafeGkeeperServer interface {
	mustEmbedUnimplementedGkeeperServer()
}

func RegisterGkeeperServer(s grpc.ServiceRegistrar, srv GkeeperServer) {
	s.RegisterService(&Gkeeper_ServiceDesc, srv)
}

func _Gkeeper_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GkeeperServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gorsovet.gkeeper/RegisterUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GkeeperServer).RegisterUser(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gkeeper_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GkeeperServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gorsovet.gkeeper/LoginUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GkeeperServer).LoginUser(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gkeeper_Greceiver_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GkeeperServer).Greceiver(&gkeeperGreceiverServer{stream})
}

type Gkeeper_GreceiverServer interface {
	SendAndClose(*ReceiverResponse) error
	Recv() (*ReceiverChunk, error)
	grpc.ServerStream
}

type gkeeperGreceiverServer struct {
	grpc.ServerStream
}

func (x *gkeeperGreceiverServer) SendAndClose(m *ReceiverResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gkeeperGreceiverServer) Recv() (*ReceiverChunk, error) {
	m := new(ReceiverChunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Gkeeper_ListObjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListObjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GkeeperServer).ListObjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gorsovet.gkeeper/ListObjects",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GkeeperServer).ListObjects(ctx, req.(*ListObjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Gkeeper_ServiceDesc is the grpc.ServiceDesc for Gkeeper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Gkeeper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gorsovet.gkeeper",
	HandlerType: (*GkeeperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterUser",
			Handler:    _Gkeeper_RegisterUser_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _Gkeeper_LoginUser_Handler,
		},
		{
			MethodName: "ListObjects",
			Handler:    _Gkeeper_ListObjects_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Greceiver",
			Handler:       _Gkeeper_Greceiver_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/gorsovet.proto",
}
